feat(game): add background
FabianVegaA/The-Wizard-Frogy pull request #1
Opened 2023-07-13 06:06 UTC by FabianVegaA

Additionally, it was added the encryption of name and score of the challenger and improved the routes
Finally, it was added unit test to support functions

2023-07-13 18:38 UTC, Camilu-png requested changes

2023-07-13 18:38 UTC, Camilu-png commented on src/Game.elm
> +    -- FIXME: get params from url
Faltó solucionar esto 👿

2023-07-13 18:38 UTC, Camilu-png commented on src/Lib/List.elm
> +rotate : Int -> List a -> List a
No se utiliza rotate ni splitAt 😐

2023-07-13 18:38 UTC, Camilu-png commented on src/Pages/Home_.elm
> +            , Effect.loadExternalUrl "/frogy"
Hay que redireccionar /frogy a /game

2023-07-13 18:38 UTC, Camilu-png commented on tests/Lib/Encrypt.elm
> +module Lib.Encrypt exposing ()
Este archivo está vacío  🙎‍♀️

2023-07-13 18:39 UTC, Camilu-png commented
Los PR deben ser más pequeños y modulares y el nombre de la rama no corresponde con los cambios.  🤦‍♀️

2023-07-14 02:41 UTC, FabianVegaA commented on src/Game.elm
> +    -- FIXME: get params from url
Solved

2023-07-14 02:41 UTC, FabianVegaA commented on src/Lib/List.elm
> +rotate : Int -> List a -> List a
Lo dejare para utilizarlo después

2023-07-14 02:41 UTC, FabianVegaA commented on src/Pages/Home_.elm
> +            , Effect.loadExternalUrl "/frogy"
Solved, thanks!

2023-07-14 02:41 UTC, FabianVegaA commented on tests/Lib/Encrypt.elm
> +module Lib.Encrypt exposing ()
Ups, removed

2023-07-14 02:49 UTC, Camilu-png approved these changes

2023-07-14 02:50 UTC, merged